config/routes.rb
Timetable::Application.routes.draw do
  resources :lines
  resources :stations
  resources :stops
  root :to => 'lines#index'
end

app/models/line.rb
class Line < ActiveRecord::Base
  has_many :stops
  has_many :stations, :through => :stops
end

app/models/station.rb
class Station < ActiveRecord::Base
  has_many :stops
  has_many :lines, :through => :stops
  validates :name, :presence => true


end

app/models/stop.rb
class Stop < ActiveRecord::Base
  belongs_to :line
  belongs_to :station
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController

 def index
  @lines = Line.all
  @stations = Station.all
 end

 def new
  @line = Line.new
 end

 def edit
  @line = Line.find(params[:id])
 end

 def show
  @line = Line.find(params[:id])
  @stops = @line.stops
  @stop = Stop.new
 end

 def update
   @line = Line.find(params[:id])

   @line.update(lines_params)
   redirect_to root_path
 end

 def destroy
  @line = Line.find(params[:id])
  @line.destroy
  redirect_to root_path
 end


 def create
  @line = Line.create(lines_params)
  redirect_to root_path
 end

 private

 def lines_params
  params.require(:line).permit(:name)
 end

end

app/controllers/stations_controller.rb
class StationsController < ApplicationController

 def index
  @stations = Station.all
 end

 def new
  @station = Station.new
 end

 def show
  @station = Station.find(params[:id])
  @stops = @station.stops
  @stop = Stop.new
end

 def edit
  @station = Station.find(params[:id])
 end

 def update
   @station = Station.find(params[:id])
   @station.update(stations_params)
   redirect_to root_path
 end

 def destroy
  @station = Station.find(params[:id])
  @station.destroy
  redirect_to root_path
 end


 def create
  @station = Station.create(stations_params)
  redirect_to root_path
 end

 private

 def stations_params
  params.require(:station).permit(:name)
 end

end

app/controllers/stops_controller.rb
class StopsController < ApplicationController


  def index
    @stops = Stop.all
  end

  def create
    @stop = Stop.create(stops_params)
    redirect_to root_path
  end


  private

  def stops_params
    params.require(:stop).permit(:line_id, :station_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lines_helper.rb
module LinesHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/helpers/stops_helper.rb
module StopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Timetable" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

          <%= yield %>

  </body>
</html>

app/views/lines/_form.html.erb
<%= form_for(@line) do |f|  %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name%>
    </div>
    <%= f.submit(:class => "btn btn-primary") %>
  <% end %>

app/views/lines/edit.html.erb
<div class="container">
  <h1>Change the name of the <%=@line.name%> line.</h1>
  <%= render 'form' %>
</div>

app/views/lines/index.html.erb
<div class="container">
  <h1> Welcome to codys bus stop app </h1>

  <%= link_to "New Bus Lines", new_line_path, :class=> "btn btn-default" %>

  <ul>
    <% @lines.each do |line| %>
      <li><%= link_to line.name, line_path(line) %> | <%= link_to "Edit", edit_line_path(line) %> | <%= link_to "Delete", line_path(line), :method => 'delete' %></li>
    <% end %>
  </ul>
  </br>
  <%= link_to "New Bus Station", new_station_path, :class=> "btn btn-default" %>
  <ul>
    <% @stations.each do |station| %>
      <li><%= link_to station.name, station_path(station) %> | <%= link_to "Edit", edit_station_path(station) %> | <%= link_to "Delete", station_path(station), :method => 'delete' %></li>
    <% end %>
  </ul>

  <%= link_to "Visualize the routes", stops_path %>
</div>

app/views/lines/new.html.erb
<div class="container">
  <h1> New Line Form </h1>
  <%= render 'form' %>
</div>

app/views/lines/show.html.erb
<div class = "container">
  <h1> Here are the stops for <strong><%= @line.name %></strong></h1>
</br>
  <ul>
  <% @stops.each do |stop| %>
    <li> <%= stop.id %> | Station: <%= Station.find(stop.station_id).name %> | </li>
  <% end %>
  </ul>

</br>
  <h2> add a station that services this line </h2>
  <%= form_for(@stop) do |f|  %>
    <div class="form-group">
      <%= f.collection_select(:station_id, Station.all, :id, :name) %>
      <%= f.hidden_field :line_id, :value => @line.id %>
    </div>
    <%= f.submit(:class => "btn btn-primary") %>
  <% end %>


</div>

app/views/stations/_form.html.erb
<%= form_for(@station) do |f|  %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name%>
    </div>
    <%= f.submit(:class => "btn btn-primary") %>
  <% end %>

app/views/stations/edit.html.erb
<div class="container">
  <h1>Change the name of the <%=@station.name%> station.</h1>
  <%= render 'form' %>
</div>

app/views/stations/new.html.erb
<div class="container">
  <h1> New Station Form </h1>
  <%= render 'form' %>
</div>

app/views/stations/show.html.erb
<div class = "container">
  <h1> Here are the stations for <strong><%= @station.name %></strong></h1>
</br>
  <ul>
  <% @stops.each do |stop| %>
    <li> <%= stop.id %> | Line: <%= Line.find(stop.line_id).name %> | </li>
  <% end %>
  </ul>

</br>
  <h2> Add a line that services this station </h2>
  <%= form_for(@stop) do |f|  %>
    <div class="form-group">
      <%= f.collection_select(:line_id, Line.all, :id, :name) %>
      <%= f.hidden_field :station_id, :value => @station.id %>
    </div>
    <%= f.submit(:class => "btn btn-primary") %>
  <% end %>


</div>

app/views/stops/index.html.erb
<div class="container">
  <h1> All Stops </h1>

  <% @stops.each do |stop| %>
    <li> <span class="stop" id="<%="#{stop.id}"%>"> <%= stop.id %></span> | <span class="station" id="<%="#{stop.station_id}"%>"> <%= stop.station.name %> </span>| <span class="line"id=<%="#{stop.line_id}"%></span> <%= stop.line.name %>
</li>
  <% end %>
</div>